INSERT INTO Unidade_Gestora (codigo_unidade_gestora, denominacao) VALUES
(1,	'Prefeitura Municipal de Florianópolis'),
(2,	'Fundo Municipal de Cinema - FUNCINE'),
(4,	'Fundação Cultural de Florianópolis Franklin Cascaes'),
(5,	'Fundação Municipal de Esportes'),
(6,	'Fundação Municipal do Meio Ambiente'),
(7,	'Instituto de Planejamento Urbano - IPUF'),
(8,	'Fundo Municipal de Habitação de Interesse Social'),
(9,	'Fundo Municipal de Saúde'),
(10, 'Fundo Municipal de Assistência Social'),
(11, 'Fundo Municipal da Criança e do Adolescente'),
(12, 'Autarquia de Melhoramentos da Capital'),
(13, 'Instituto de Geração de Oportunidades - IGEOF'),
(14, 'FUMDESF - Fundo Municipal Promoção Empreendimento Desenvolvimento Comercial, Industrial, Rural e Marinho'),
(16, 'Fundo Municipal de Saneamento'),
(17, 'Câmara Municipal de Florianópolis'),
(19, 'Fundo Municipal de Emergência da Defesa Civil'),
(20, 'Fundo Municipal de Turismo'),
(21, 'Fundo Municipal do Idoso'),
(22, 'Instituto de Previdência Social dos Servidores Públicos'),
(23, 'Fundo Municipal de Inovação'),
(24, 'Fundo Municipal de Trânsito'),
(25, 'Fundação Rede Solidária Somar Floripa'),
(55, 'IPREF – Instituto de Previdência de Florianópolis')
ON CONFLICT (codigo_unidade_gestora) DO NOTHING;